version: '3.8'

services:
  wan2-flf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wan2-flf-local
    command: ["--rp_serve_api", "--rp_api_host=0.0.0.0", "--rp_api_port=8080"]
    ports:
      - "8081:8080"  # RunPod API
      - "8189:8188"  # ComfyUI Web UI (different port to avoid conflict)
    volumes:
      # Input/Output directories
      - ../input:/comfyui/input
      - ./output:/comfyui/output
      # Model directories - mount from host if available
      - ./models:/comfyui/models
      # Test input
      - ./test_input.json:/test_input.json:ro
      # HuggingFace cache
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - SERVE_API_LOCALLY=true
      - NVIDIA_VISIBLE_DEVICES=all
      # ComfyUI settings
      - COMFYUI_DISABLE_METADATA=false
      # Default FLF parameters
      - START_IMAGE=${START_IMAGE:-start.jpg}
      - END_IMAGE=${END_IMAGE:-end.jpg}
      - POSITIVE_PROMPT=${POSITIVE_PROMPT:-smooth transition animation between frames}
      - NEGATIVE_PROMPT=${NEGATIVE_PROMPT:-static, blurry, low quality, mouth opening, talking}
      - WIDTH=${WIDTH:-720}
      - HEIGHT=${HEIGHT:-1280}
      - LENGTH=${LENGTH:-81}
      - STEPS=${STEPS:-20}
      - SEED=${SEED:-42}
      - FPS=${FPS:-16}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 10s
      retries: 3